{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
module Paper where

import           Control.Lens ((^.))
import           Control.Monad.RWS
import           Control.Monad.State.Strict (modify)
import           Data.Default (def)
import           Data.List (break)
import           Data.Monoid ((<>))
import           Data.Functor.Identity
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Text    as Text
import qualified Data.Text.IO as Text
import           Text.Authoring
import           Text.Authoring.TH
import           Text.LaTeX.Base.Syntax (LaTeX(..),TeXArg(..))
import           Text.LaTeX.Base.Writer (LaTeXT(..), execLaTeXT)
import qualified Text.LaTeX as LTX

import           Paper.SectionModel (sectionModel)
import           Paper.SectionMatchedFilter (sectionMF)
import           Paper.SectionObservation (sectionObservation)
import           Paper.SectionCrossSection (sectionCrossSection)
import           Paper.SectionAcknowledgement (sectionAcknowledgement)


writePaper :: FilePath -> FilePath -> FilePath -> IO ()
writePaper srcFn outFn bibFn = do
  srcStr <- Text.readFile srcFn
  print $ (srcFn, outFn)

  (bodyText,bibText) <- genBodyText

  let
    (<?) = Text.isInfixOf
    rep str
      | "Insert abstract here" <? str      = abstractText
      | "Insert document body here" <? str = bodyText
      | otherwise                          = str

  Text.writeFile outFn $
    Text.unlines $
    map rep $ Text.lines srcStr

  Text.writeFile bibFn bibText

abstractText :: Text.Text
abstractText = LTX.render abstract

abstract :: LaTeX
abstract = TeXRaw "We study the possibility of observationally distinguishing lightning models in protoplanetary disks."


genBodyText :: IO (Text.Text, Text.Text)
genBodyText = do
  let paper = do
        sectionIntro
        sectionModel
        sectionObservation
        sectionMF
        sectionConclusion
        sectionAcknowledgement
        
        [rawQ| \appendix |]

        sectionCrossSection         

  
  (bibText, _ , bodyDoc) <- runAuthoringT $ do
    withDatabaseFile "material/citation.db" paper
    txt <- bibliographyContent
    return txt



  return (LTX.render bodyDoc, bibText)

sectionIntro :: MonadAuthoring s w m => m ()
sectionIntro = do
  command1 "section" $ raw "Introduction"
  
  [rawQ| 
There has been a controversial debate on the existence and the mechanism of
protoplanetary disk lightning. 
@{citet ["doi:10.1006/icar.1997.5846"]} argued that plasma conductivity is too large
for the lightning to take place.
@{citet ["bibcode:1998A&A...331..121P"]}
argued that unknown, efficient grain-grain charging process
is required to produce lightning.
Despite of these barriers, mechanisms that leads to lightning are proposed:
dust-dust collisional charging @{citep ["bibcode:2000Icar..143...87D","bibcode:2010MNRAS.401.2641M"]};
mutual positive feedback of thermal ionization and Joule heating @{citep ["bibcode:2012ApJ...761...58H","bibcode:2013ApJ...767L...2M"]}; electric field generated by magnetorotational instability (MRI)
 @{citep ["bibcode:2005ApJ...628L.155I","bibcode:2012ApJ...760...56M"]}.
Chondrules included in meteorites carry unmodified materials from the protoplanetary disks that formed 
our Solar System that exhibit evidences of lightning
@{citep ["bibcode:2000M&PS...35..537W"]}.

Meanwhile,  these twenty years saw progress  in the understanding of the lightning ignition mechanism.
Attempts has been made to reveal the mechanism that can cause discharge at the electric field strength 
well below the nominal dielectric strength of air
@{citep ["doi:10.1029/JC076i024p05799", "doi:10.1063/1.1656844"]}. As a result 
new model of lightning such as Runaway breakdown
@{citep ["doi:10.1016/0375-9601(92)90348-P", "doi:10.1070/PU2001v044n11ABEH000939"]}
has been proposed. We take such new models into account and propose new observational feature for
protoplanetary disk lightning. 
Observation of the disk lightning will contribute to the
understanding of the electromagnetic process in the protoplanetary disk,
and the source of chondrule heating.


Electric field $E$ in protoplanetary disk can be generated by
Magnetorotational instability (MRI) or by collective motion of charged dust.
The breakdown model sets upper limit $E \leq E_{\rm crit}$ to the electric field amplitude.
At the point $E = E_{\rm crit}$ electric discharge takes place, which increases the ionization degree of the medium
and prevents the further growth of the electric field amplitude.
Lightning bolts, contrary to intuition, does not serve as the only dominant observational signal emitter.
This is because lightning is transient events, and typical radius of a lightning bolt $5000 l_{\rm mfp}$
@{citep ["bibcode:1992ApJ...387..364P"]}
is much smaller than the scaleheight. Most of the protoplanetary disk gas is containd in the region
outside the lightning bolts. 
We call this lightning matrix gas (LMG).
The properties of LMG is no different from those of the disk gas without lightning,
but differs in one point that LMG is subject to
electric field $E \simeq E_{\rm crit}$. We study the observational feature of the LMG.


 |]

sectionConclusion :: MonadAuthoring s w m => m ()
sectionConclusion = do
  let takahashi2007 = citet ["isbn:9784130627184"]
      marlow2013    = citet ["isbn:9781449335946"]
      keithWardle   = citep ["bibcode:2014MNRAS.440...89K"]

  command1 "section" $ esc "Conclusions and Discussions."
  [rawQ|   

  todo: @{keithWardle} discusses circumplanetary disk lightning.


   We have shown that some
   lightning models are observationally distinguishable with ALMA.
   It is possible to reject some of the lightning models based on ground observations.
   Our lightning models treated here are very simple. To apply this work to more realistic
   disk models are beyond the scope of this paper, and left as a useful direction
   for future research.
   This work is based on the landmark review of terrestrial lightning by @{takahashi2007}. 
   The parallel computations used in this work are based on @{marlow2013}.


   |]
